### ISSUE TITLE
Extends with new styles

### ISSUE THREAD

**Issue by HugoDerigny** [dapi-labs/react-nice-avatar#39]
Hi ! 

First of all thanks for you work, it's a very nice and useful open source project.

I wanted to know if you have planned to extends the library with some new hairs, hats or shirts style ?
I know i could do it myself but it won't be as good as your work.

**Comment by wwayne** [comment]
Hi, I don't have a plan to extend the style sorry :(
The original design file can be found here https://www.figma.com/community/file/829741575478342595 , might be helpful if you wanna extend yourself
