### ISSUE TITLE
Error: Minified React error #130

### ISSUE THREAD

**Issue by SarsilAdmin** [dapi-labs/react-nice-avatar#42]
Hello guys,

First of all, really nice job! I loved the avatars and their stylings.

I am developing a react web app using your avatar, I follow the implementation guide, but and it worked.
I could build and run locally my web app and all work fine.
But when I deploy into Netlify, I am getting the follow error when I open the app:

`Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

After some tests, I remove the uses of this lib, and when I remove all work properly.
I did same reseach and I think it's something about the default export of the component.

Here is my implementation:

- Importation

`
import ReactNiceAvatar, { genConfig, NiceAvatarProps } from 'react-nice-avatar';
`

- My Component

`
export function UserAvatar({ ...rest }: AvatarProps) {

    const { userData } = useAuthentication();

    const { isOpen, onClose, onOpen } = useDisclosure();

    const config = {
        "sex": 'man',
        "faceColor": '#E5B5A1',
        "earSize": 'small',
        "hairColor": '#000',
        "hairStyle": 'normal',
        "hatStyle": 'none',
        "hatColor": '#000',
        "eyeStyle": 'oval',
        "noseStyle": 'short',
        "mouthStyle": 'smile',
        "shirtStyle": 'short',
        "glassesStyle": 'none',
        "hairColorRandom": false,
        "isGradient": false,
        "shape": 'circle',
        "shirtColor": theme.colors.sarsil.orange,
        "bgColor": theme.colors.gray[50]
    } as NiceAvatarProps;

    const myConfig = genConfig(config);

    return (
        <Flex
            as='button'
            cursor='pointer'
            onClick={onOpen}
        >
            {!!userData?.avatar ? (
                <Box
                    w='15rem'
                    h='15rem'
                    bgColor='gray.50'
                    borderRadius='50%'
                    boxShadow='md'
                    p='1px'
                    {...rest}
                >
                    {!!myConfig && (
                        <ReactNiceAvatar
                            style={{ width: '100%', height: '100%' }}
                            {...myConfig}
                        />
                    )}
                </Box>
            ) : (
                <Center borderRadius='50%' p='4' bgColor='gray.50'>
                    <Icon as={HiOutlineUser} fontSize='1.5rem' color='sarsil.orange' />
                </Center>
            )
            }
            <AvatarModal isOpen={isOpen} onClose={onClose} />
        </Flex >
    );
}
`

**Comment by wwayne** [comment]
Hi, not sure if it is related to `myConfig`, can you check if `theme.colors.sarsil.orange` and `theme.colors.gray[50]` return the correct result?

**Comment by SarsilAdmin** [comment]
I have tried to generating the config using constants colors string, but the result was the same. Those variables return the hex string of theme color, I printed it, and the return is #FF5224 and #EEEEF2, respectively.

**Comment by wwayne** [comment]
sorry no idea... is it normal in your local? We might able to get a better error msg if we can reproduce in the local

**Comment by SarsilAdmin** [comment]
Local is working fine, that's the strangest part. And both of builds, locally and on netlify, are creating the dist package normally, without any error.

**Comment by wwayne** [comment]
yeah that would be hard for the investigation haha
I searched another react avatar library for you so you won't stuck on this avatar issue https://github.com/boringdesigners/boring-avatars
