### ISSUE TITLE
Layout issue when using textAlign: "center" wrap

### ISSUE THREAD

**Issue by jzombie** [dapi-labs/react-nice-avatar#47]
If using using inside of a text-align center container, a wrapping container w/ text-align left seems to be needed to prevent layout issues:

**w/o fix**
![Screen Shot 2023-04-07 at 11 35 58 AM](https://user-images.githubusercontent.com/1139657/230652800-3cc9f88a-7c84-4ee1-94cc-4ef62803b92e.png)

**w/ fix**
![Screen Shot 2023-04-07 at 11 39 35 AM](https://user-images.githubusercontent.com/1139657/230652950-f75bd39a-62df-41c6-a523-f8feb8bbdacc.png)

**Comment by wwayne** [comment]
Hi I did some try in my local but I can't reproduce the issue
my understanding is the text align center won't make it look like that, it might effected by other CSS issues, not sure

<img width="270" alt="屏幕截图 2023-04-08 080926" src="https://user-images.githubusercontent.com/5305874/230694538-5e755bd3-e8e7-488f-96e9-7534584a2be5.png">
