### ISSUE TITLE
getConfig not working properly

### ISSUE THREAD

**Issue by amitroy-thedev** [dapi-labs/react-nice-avatar#50]
when i'm using this method to generate man avatar it is also generating female avatar sometimes..
is this the correct way of doing it or am i doing something wrong ?
Please help me with this
`const config = genConfig({ sex: "man" }) `

**Comment by wwayne** [comment]
Hi, the usage looks correct
what female avatar you saw when using such config? like long hair?

**Comment by amitroy-thedev** [comment]
@wwayne 
Not long but the normal one which is for female avatar

**Comment by wwayne** [comment]
can you give me a snapshot if possible? might be helpful for my debug, thanks : )
I will take a check when I have time

**Comment by amitroy-thedev** [comment]
![IMG20230611160955](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/572ce350-cd00-4020-9c1f-d7b7d0ad6303)
![IMG20230611161018](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/7f467c8c-71c1-49d8-b7d7-2f74b1c651d4)
![Screenshot_2023-06-11-16-07-47-78_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/8cf69e6c-0b8b-427d-932c-e1d6f9d4016b)

**Comment by amitroy-thedev** [comment]
![IMG_20230611_162717](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/305b2aef-3fa9-420d-8ab0-2c334ae8036b)
![IMG20230611161018](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/4472fcc2-491c-476b-a775-877e23f06fec)
![IMG_20230611_162734](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/8f46c9af-ac19-4793-b0b3-e7318b2599d3)

**Comment by wwayne** [comment]
I see, the hairstyle in the screenshot named `normal` and it is used for both man and woman.
One solution would be picking a hairstyle yourself and pass it into the config, example:
```js
const hairStyles = ["thick", "mohawk"];
const randomHairStyle = hairStyles[Math.floor(Math.random() * hairStyles.length)];
const config = genConfig({ sex: "man", hairStyle: randomHairStyle })
```

**Comment by amitroy-thedev** [comment]
@wwayne
Okay 👍 I'll try that ...
Thank you

**Comment by amitroy-thedev** [comment]
@wwayne it really worked...Thanks 😊

**Comment by amitroy-thedev** [comment]
![IMG_20230611_193942](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/feda581c-7a34-4095-b7ef-7b9be6c49463)
Some issues is printing in my console.
 I've coded that if sex is male then it should pick randomManHairstyle or else randomWomanHairstyle

**Comment by amitroy-thedev** [comment]
@wwayne 
Can you help me with something if you have time..
Actually i want to make user avatar downloadable can you please help me to do that..

**Comment by wwayne** [comment]
I have a download feature for the demo page, for your reference https://github.com/dapi-labs/react-nice-avatar/blob/main/demo/src/App/index.tsx#L40-L55
it relies on the lib `dom-to-image`

**Comment by amitroy-thedev** [comment]
@wwayne 
I've seen that but it was resolving my problem.. actually i want that whenever user signup he get some random avatar which sticks with his profile (it should not change everytime) ..for that I need to store it in useState but the problem is how do I store it

**Comment by wwayne** [comment]
can you get the user's id, email or some unique stuff, if so you can use it like the following:
```
const config = genConfig("STRING_OF_ID_OR_STH") 
```
but this way you can't specify other options like sex, etc

**Comment by amitroy-thedev** [comment]
@wwayne ya i can

**Comment by wwayne** [comment]
if it not working for your case, I guess you have to save the config into the database and fetch it from the db to the frontend every time you use the avatar

**Comment by amitroy-thedev** [comment]
Ya you're right i was feeling the same..
But now the problem is i cannot specify with sex or other stuffs 🥲

**Comment by wwayne** [comment]
The error image you posted above looks is because this line 
```
 const config = genConfig({ sex: {sex}, hairStyle: sex === "man" ? randomManHairStyle : randomWomanHairStyle });
```

sex: {sex} should be sex: sex

**Comment by amitroy-thedev** [comment]
But it still working fine with that 🤔

**Comment by amitroy-thedev** [comment]
thanks..now its not logging any warning

**Comment by amitroy-thedev** [comment]
![IMG20230613225402](https://github.com/dapi-labs/react-nice-avatar/assets/104709542/4a32bebc-c2de-4684-a9a4-61dda47101af)
HairStyleMan and HairStyleWoman both have "normal" value ..i guess this is the reason why man is also showing woman hair sometimes

**Comment by wwayne** [comment]
yeah that's correct

**Comment by amitroy-thedev** [comment]
I want to correct it would you please me how to do that from my side...

**Comment by amitroy-thedev** [comment]
I want to correct it would you please say how to do it from my side ..

**Comment by wwayne** [comment]
sorry I don't know what's your problem, are u saying how do you use genConfig('id_string') and specify sex and hairstyle? if so, I don't think it is possible atm, maybe I can improve it in the future but don't have time for the moment

**Comment by amitroy-thedev** [comment]
Okay...
