### ISSUE TITLE
Warning: Prop `id` did not match. Server: "mask2091363" Client: "mask5678949"

### ISSUE THREAD

**Issue by jsvelte** [dapi-labs/react-nice-avatar#51]
When I try to reload the page it give me this annoying error and I spent days how to fix it 

client.js:1 Warning: Prop `id` did not match. Server: "mask2091363" Client: "mask5678949"
    at mask

**Comment by wwayne** [comment]
Not sure if it helps if u are using next.js https://stackoverflow.com/a/67177512/3404325
try using next/dynamic

**Comment by jsvelte** [comment]
I fixed the issue using dynamic import @wwayne 

import dynamic from 'next/dynamic'
const ReactNiceAvatar = dynamic(async () => await import('react-nice-avatar'), { ssr: false })

**Comment by guotie** [comment]
maybe face maskId should not use random to avoid this question.

**Comment by wwayne** [comment]
Thanks @guotie for the suggestion
I remove the random id and publish a new version v1.5.0, hope it can fix the potential SSR issue
